### ISSUE TITLE
Trusted Platform Details

### ISSUE THREAD

**Issue by bharveyTX** [CC-in-the-Cloud/Admin#101]
We need to create a new top-level section that expounds upon the definition of Trusted Platform in the glossary and provide details on how the Trusted Platform is to be incorporated within CCiTC guidance. 

Should probably be created somewhere after Shared Security Model and before Contributors Roles sections.

**Comment by jgb1128** [comment]
What are the essential things to include?
Acceptable cloud authorizations (what is not acceptable...that is up to the scheme)
For Platform technologies:  GPOS, Virtualization, "Gear, Compute Infrastructure, Network infrastructure.

**Comment by mfa00007** [comment]
IMHO - we could tie this into the deployed configuration (AGD) - or as part of the assumptions.  (Otherwise we will have an issue with the cloud deployment meeting a specific scheme for certification or not. )

**Comment by jgb1128** [comment]
Recommendation for this is a bottom's up approach:  List out a set of Assumptions derived from existing interesting PPs.  Note that PP authors need to revise PPs to provide wording about how a CSP will meet those assumptions. For example:
A.PHYSICAL PROTECTION:  Any CSP worth its salt would meet this easily.  Authors should expand (preferably with wording from acceptable cloud authorization schemes) on expectations to meet this requirement; however it is not expected in the PP that the actual requirements would be noted as these are assumptions and therefore not to be evaluated other than confirming that they are satisfied by a cloud authorization.

**Comment by tstodart** [comment]
So the concept would be that we would provide a set of assumptions that would be satisfied by a 'trusted platform'. Similarly, to A.PHYSICAL_PROTECTION, there are some assumptions in the NDcPP around Isolation, trusted admin (of the platform), credential security, residual information, connectivity. that would be included. These would 'fill in' some of the gaps we are probably seeing in current PP's SPDs and as was done for MDM, we can determine whether these are satisfied by (for example) Fedramp. PP writers would then incoporate these into their own PP's for TOE's in the cloud.

An initial list of 'candidate' assumptions from PP's of note are:
A.PLATFORM generally talks about platform integrity and trust. A.MDM_SERVER_PLATFORM goes into more detail and looks interesting.
A. TRUSTED/PROPER-ADMIN. This was thought to be relevant, but we should probably separate activities at the TOE level and platform level (see A.TRUSTED-PLATFORM-ADMIN below).
A.PHYSICAL PROTECTION. Only seen in some PP’s – would seem important for Cloud platform since it obviously has to fulfil this.
A.LIMITED_FUNCTIONALITY/A.NO_GENERAL_PURPOSE. Found on NDCPP and DBCPP. Limits server to only one function and not have general compute available – could be platform configuration.
A.(VS)REGULAR_UPDATES. Found on GPCP and NDCPP. Makes sense to consider this as a rationale for regular cloud updates (at possibly every level).
A.ADMIN_CREDENTIALS_SECURE – Administrators credentials (private keys) are protected by the platform on which they reside. Makes sense for cloud.
A.RESIDUAL_INFORMATION. Found on NDCPP. How does the cloud infrastructure handle sensitive residual information on equipment when it is discarded or removed from operational environment – seems very relevant.
A_VS_TRUSTED_ADMINISTRATOR. From vND’s for NDCPP, around administration of the VS. We should probably have something equivalent A.TRUSTED-PLATFORM-ADMIN)
A.VS-ISOLATION. From vND’s for NDCPP. Concerning sufficient isolation between s/w running in VMs and that the VS itself is protected from the software running inside. This is probably a critical assumption that should be considered for our scenario (e.g A.PLATFORM_ISOLATION)
A.VS_CORRECT_CONFIGURATION. From vND’s for NDCPP. Seems we should have something similar (A.PLATFORM_CORRECT_CONFIGURATION) probably linked to guidance.
A.CONNECTIVITY/A.CONNECT: Found in NDCPP and DBCPP. While the meanings are a little different, it would seem that in addition to isolation, we are missing some assumptions on what the cloud platform provides in terms of network connectivity and the integrity/confidentiality of those. The DBCPP ‘A.CONNECT’ should be considered as a base.

**Comment by tstodart** [comment]
https://www.cisco.com/c/en/us/about/trust-center/compliance/ccf.html#~what-is-the-cloud-controls-framework

**Comment by mfa00007** [comment]
Given the amount of assumptions on the cloud environment - for 'security' should we look at making an Assumption or assignment to the Operating Environment - 
i.e. :
A.Cloud - cloud environment has been [vetted/certified/conforms] to a secure configuration 
A.Cloud - cloud environment has matches a [vetted/certified/conforming] configuration
OE.Cloud - cloud environment has been evaluated and [complies with, certified as] security requirements.....

**Comment by GY5318** [comment]
Tried downloading the file 3 times but the Captcha keeps failing. Anybody
have the file?

Regards

Greg

 

DISA Chief Mobility Eng., MEng

DoD APL Mobility Manager 

SD5 Enterprise Mobility Div. / DISA

Phone (301) 225-9501 <tel:(301)%20225-9501> 

Cell: (571) 481-7514 <tel:(571)%20481-7514> 

DSN (312) 375-9501 <tel:(312)%20375-9501> 

DMCC-S: (302) 841-1412 <tel:(302)%20841-1412> 

ECVoIP: (302) 375-0686 <tel:(302)%20375-0686> 

U: ***@***.*** ***@***.***> 

S: ***@***.***
***@***.***> 

IC: ***@***.*** ***@***.***>

**Comment by tstodart** [comment]
> Tried downloading the file 3 times but the Captcha keeps failing. Anybody have the file? Regards Greg DISA Chief Mobility Eng., MEng DoD APL Mobility Manager SD5 Enterprise Mobility Div. / DISA Phone (301) 225-9501 <tel:(301)%20225-9501> Cell: (571) 481-7514 <tel:(571)%20481-7514> DSN (312) 375-9501 <tel:(312)%20375-9501> DMCC-S: (302) 841-1412 <tel:(302)%20841-1412> ECVoIP: (302) 375-0686 <tel:(302)%20375-0686> U: ***@***.*** ***@***.***> S: ***@***.*** ***@***.***> IC: ***@***.*** ***@***.***> From: tstodart ***@***.***> Sent: Wednesday, July 26, 2023 11:44 AM To: CC-in-the-Cloud/General ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [CC-in-the-Cloud/General] Trusted Platform Details (Issue #101) https://www.cisco.com/c/en/us/about/trust-center/compliance/ccf.html#~what-i s-the-cloud-controls-framework <https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fwww.cisc o.com%2Fc%2Fen%2Fus%2Fabout%2Ftrust-center%2Fcompliance%2Fccf.html%23~what-i s-the-cloud-controls-framework&data=05%7C01%7Cgregory.f.youst.civ%40mail.mil %7C218beed41997447bd84d08db8def3a90%7C102d0191eeae4761b1cb1a83e86ef445%7C0%7 C0%7C638259830850423696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoi V2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5ZmjF0K9od5bzYT xGK4C1bWn4edz%2BHSt8bLhHN5d7Pc%3D&reserved=0> - Reply to this email directly, view it on GitHub <https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c om%2FCC-in-the-Cloud%2FGeneral%2Fissues%2F101%23issuecomment-1652078022&data =05%7C01%7Cgregory.f.youst.civ%40mail.mil%7C218beed41997447bd84d08db8def3a90 %7C102d0191eeae4761b1cb1a83e86ef445%7C0%7C0%7C638259830850423696%7CUnknown%7 CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0 %3D%7C3000%7C%7C%7C&sdata=jCx1OvsyQxSM2NMQuiJwEMz15vcOI8ih%2Fh1gt9XOf5c%3D&r eserved=0> , or unsubscribe <https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c om%2Fnotifications%2Funsubscribe-auth%2FAU6AIDVO3QVSDOZNPTNF7U3XSE3NXANCNFSM 6AAAAAA2KRJR3A&data=05%7C01%7Cgregory.f.youst.civ%40mail.mil%7C218beed419974 47bd84d08db8def3a90%7C102d0191eeae4761b1cb1a83e86ef445%7C0%7C0%7C63825983085 0423696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6 Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F61Ky4u%2FKlw8F%2F0glQMok9vZ8pa 9Aso4T36ttZPUVd8%3D&reserved=0> . You are receiving this because you are subscribed to this thread. <https://github.com/notifications/beacon/AU6AIDV6VQ6BUHWRZBVHRGLXSE3NXA5CNFS M6AAAAAA2KRJR3CWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTT CPC24M.gif> Message ID: ***@***.*** ***@***.***> >

Resolved

**Comment by tstodart** [comment]
> Given the amount of assumptions on the cloud environment - for 'security' should we look at making an Assumption or assignment to the Operating Environment - i.e. : A.Cloud - cloud environment has been [vetted/certified/conforms] to a secure configuration A.Cloud - cloud environment has matches a [vetted/certified/conforming] configuration OE.Cloud - cloud environment has been evaluated and [complies with, certified as] security requirements.....

I like it a lot (as a cloud vendor) - effectively that clould is awesome and solves all. However, I think the Security Objectives Rationale will look weird for each PP since there will be multiple 'A.x/OE.x' for non-cloud but only the 'A.x/OE.x' for TOEs in the cloud - effectively saying all are merged into one. Might also be more difficult for PP writers to incorporate into their existing versions, vs. a set of assumptions that look very similar to what we already see in PP's. We'll also not be able to do the detailed mapping to (e.g.) Fedramp controls since A.Cloud/OE.Cloud becomes a 'catch-all' without any detail (e.g. physical/network/isolation, etc.). I am not sure schemes will necessarily be comfortable with that. It may also be harder for an evaluator if they need to resolve an SFR that is relying on something provided by the platform (e.g timestamp) if all the can do is point to 'A.Cloud/OE.Cloud'. Just my thoughts.

**Comment by tstodart** [comment]
After previous discussions around threats I have added a para to the text. For the PP's used as inputs, threats are written without reference to the environment (as an adverse action performed by a threat agent on an asset per CC pt 1) and therefore don't map to assumptions or Security Objectives of the operating environment. But it may make sense for a PP author to review the threats in the context of the TOE running on a cloud platform.

**Comment by jgb1128** [comment]
Closed now integrated.
