### ISSUE TITLE
Guidance for Schemes

### ISSUE THREAD

**Issue by bharveyTX** [CC-in-the-Cloud/Admin#106]
We need to formulate our position on how schemes will develop policies for Trusted Platform acceptance. 

We will outline how CC certificates can be composed to create a Trusted Platform and how to leverage cloud authorization schemes if no CC certs are available.

**Comment by bharveyTX** [comment]
We will also use this issue to track suggestions for implementing guidance on Data Sovereignty.

**Comment by compgeeksquires** [comment]
Brought over potential definition from closed issue:
Possible Data sovereignty definitions:
From https://www.techtarget.com/whatis/definition/data-sovereignty:
"Data sovereignty is the concept that information which has been converted and stored in binary digital form is subject to the laws of the country in which it is located."

longer option: from https://cloudian.com/guides/data-protection/data-sovereignty-in-the-cloud-key-considerations/
"Data sovereignty refers to the laws applicable to data because of the country in which it is physically located. The legal rights of data subjects (any individual whose personal information is being gathered, retained, or processed), and data protection requirements, depend on the location in which their data is stored. Accordingly, organizations will have different responsibilities for data in different geographical locations.

Data sovereignty is distinct from data localization and data residency:

Data localization refers to a governmental policy that prohibits organizations from transferring data outside a specific location. It is a special case of data sovereignty.
Data residency is a decision by businesses to store data in a specific geographical location. Organizations might store data in a specific location to avoid legal requirements, take advantage of tax regimes, or for performance reasons. Once an organization chooses a location for its data, it is subject to data sovereignty—the laws applicable in that region."

**Comment by tstodart** [comment]
Some generalised text based on where I see call-outs regarding the scheme in the current guidance (so a bit of a copy-and-paste). We probably need to tidy up the terms used (e.g. Evaluation Authorities/schemes) throughout the document. Can be used as a start for discussion:

Evaluation Authorities for schemes should review carefully this guidance and any PP that is being used for an evaluation of a TOE in a cloud environment, and confirm that there are no conflicts with existing Evaluation Authority policies (for example, a requirement for the evaluator have the the TOE physically located or tested in their own facility).
Evaluation Authorities should consider to provide their own policies regarding Trusted Platform acceptance criteria in order to support the evaluation efforts. The Protection Profile should provide guidance for an evaluator to assess whether the cloud environment for the TOE satisfies the Security Objectives of the Operating Environment of the PP. This may likely include a mapping to Cloud Authorisation Scheme(s) that the Evaluation Authority may recognise as providing assurance that the requirements are met, and may provide input for an Evaluation Authority policy.
Evaluation Authorities should review the evaluator evidence provided regarding the establishment of their test environment for the cloud. The evidence provided by the evaluator (that their environment establishes controls provided by the CSP to ensure effective isolation equivalent to on-prem testing to maintain the integrity of results) should be carefully reviewed. 
Evaluation Authorities should also review the PP's guidance around vulnerability testing and confirm that the evaluator has considered that guidance. The evaluator evidence should demonstate that the evaluator was able to utilize cloud attack vectors. I.e. service portal, management plane, etc. to complete the testing.

**Comment by bharveyTX** [comment]
We have dropped this into the guidance for additional review.

**Comment by jgb1128** [comment]
Change suggested:
"This may likely include a mapping to Cloud **Authorization** Scheme(s) that the Evaluation Authority may **recognize** as providing assurance that the **security objectives of the operating environment** are met, and may provide input for an Evaluation Authority policy."

**Comment by bharveyTX** [comment]
> Change suggested: "This may likely include a mapping to Cloud **Authorization** Scheme(s) that the Evaluation Authority may **recognize** as providing assurance that the **security objectives of the operating environment** are met, and may provide input for an Evaluation Authority policy."

Change implemented.

**Comment by bharveyTX** [comment]
Closed per discussion.
