### ISSUE TITLE
Review the new draft Terms of Reference

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#124]
Team:
As a part of our condition to become a Technical Community, the CCDB wants to review and approve our Terms of Reference (ToR).  Brandon and I made some very minor changes to the ToR mostly changing the name and references that we felt needed to be changed before submitting the ToR.  We also added more specific information around how to join the TC and that we are now using GitHub.  Unfortunately we cannot publish a new ToR without a vote.  Please review the ToR. I am giving everyone until Nov 29th to do that....which takes us out to December 4th. Log issues you have and suggestions on this issue as a comment. We can discuss them on the call Nov 29th.
After that I will call for a vote, and that period will be two weeks; with voting completing on December 20th.

You can view and download the new [version](https://github.com/CC-in-the-Cloud/General/blob/Editorial-/iTC%20Admin%20Docs/iTC-ToR.pdf).

Thanks all

**Comment by ecbconnor** [comment]
Editorial comments:
1. Can Version and Date information be added to the document and repeated in page footers?
2. Is it possible to include redline and strikeout markings on drafts for review?

General curiosity: Is it normal for iTCs to require at least 2/3 "yes" as well as less than 1/4 "no" votes to carry a resolution?  Especially if abstentions are not counted (as I understand the text).

Otherwise looks good!

**Comment by heimannrj** [comment]
In Section 3, I am not sure you need to provide a rationalization for keeping a separate document of Key Persons separate from this ToR.  I would simply state where to find it and move on.

**Comment by heimannrj** [comment]
Section 4 indicates that CCUF and GitHub are the collaboration spaces but the application process to join (Section 6.1)  the TC appears to be a google cloud based doc.  Maybe move the application form to CCUF or GitHub?

**Comment by gnickells** [comment]
- +1 for including version/date information on the title page

- Section 1 'Identification' - Lingering reference to "International" technical community.

- Section 3 'Key Persons/Affiliations' - Lingering reference to "iTC"

- Section 3 'Key Persons/Affiliations' - Section title states "Key Persons" but "Key Roles" are mentioned in the section, perhaps a one-liner would be helpful explaining that the induction of key persons to fill critical roles within the TC to align with other TC's and iTC's to maintain order, structure, and leadership of the community.

- Section 5.1 'Application of the White Paper' - Reference to CCitC "Working Group" should this be "Technical Community" instead?

- Section 6.1 'Membership' - Two lingering references to "iTC"

- Section 6.6.2 'Technical decisions' - Three lingering references to "iTC"

- Section 6.6.2 'Technical decisions' Bullet 3 - "...they can request the reason for the objection to be documented." propose change to "...they can request the reason for objection to be documented by CCitC Management."

- Section 6.6.2 'Technical decisions' Bullet 4 - "Once a decision has been made by the group..." propose change to "Once a decision has been made by the TC". 

-  Section 6.7 'Voting' - Numerous references to "iTC"

- Section 6.7.2 and 6.7.3 - references to "iTC"

- Section 6.10.3 'Work product ownership' - First sentence should be removed due to references of CPP & SD

- Section 6.11 'Inappropriate topics' - lingering reference to "iTC"

**Comment by jgb1128** [comment]
> Editorial comments:
> 
> 1. Can Version and Date information be added to the document and repeated in page footers?
> 2. Is it possible to include redline and strikeout markings on drafts for review?
> 
> General curiosity: Is it normal for iTCs to require at least 2/3 "yes" as well as less than 1/4 "no" votes to carry a resolution? Especially if abstentions are not counted (as I understand the text).
> 
> Otherwise looks good!

Yes we can add Version and Date.

Redlining is challenging but we can look into it.

**Comment by tsc-n** [comment]
Section 2 , 4th sentence, has a typo “proudcts”  instead of “products”

**Comment by jgb1128** [comment]
Proposal: remove "Not more than one-quarter of the Counted votes cast are negative."  Leave the rest as is (in section 6.7)

**Comment by jgb1128** [comment]
Roger:  remove Abstentions "are not considered to be" Counted votes in the final total.

Should read: Abstentions are not Counted votes in the final total.

**Comment by jgb1128** [comment]
> In Section 3, I am not sure you need to provide a rationalization for keeping a separate document of Key Persons separate from this ToR. I would simply state where to find it and move on.

Agree we will simplify.  Also remove references to Team Lab

**Comment by jgb1128** [comment]
> Section 4 indicates that CCUF and GitHub are the collaboration spaces but the application process to join (Section 6.1) the TC appears to be a google cloud based doc. Maybe move the application form to CCUF or GitHub?

Thanks.  We will try this for now.

**Comment by jgb1128** [comment]
> * +1 for including version/date information on the title page
> * Section 1 'Identification' - Lingering reference to "International" technical community.
> * Section 3 'Key Persons/Affiliations' - Lingering reference to "iTC"
> * Section 3 'Key Persons/Affiliations' - Section title states "Key Persons" but "Key Roles" are mentioned in the section, perhaps a one-liner would be helpful explaining that the induction of key persons to fill critical roles within the TC to align with other TC's and iTC's to maintain order, structure, and leadership of the community.
> * Section 5.1 'Application of the White Paper' - Reference to CCitC "Working Group" should this be "Technical Community" instead?
> * Section 6.1 'Membership' - Two lingering references to "iTC"
> * Section 6.6.2 'Technical decisions' - Three lingering references to "iTC"
> * Section 6.6.2 'Technical decisions' Bullet 3 - "...they can request the reason for the objection to be documented." propose change to "...they can request the reason for objection to be documented by CCitC Management."
> * Section 6.6.2 'Technical decisions' Bullet 4 - "Once a decision has been made by the group..." propose change to "Once a decision has been made by the TC".
> * Section 6.7 'Voting' - Numerous references to "iTC"
> * Section 6.7.2 and 6.7.3 - references to "iTC"
> * Section 6.10.3 'Work product ownership' - First sentence should be removed due to references of CPP & SD
Proposed change: "No copyrights will be asserted on the work products produced the Cloud-TC."
> * Section 6.11 'Inappropriate topics' - lingering reference to "iTC"

**Comment by jgb1128** [comment]
All updated in latest versions.
