### ISSUE TITLE
Comments on "Guidelines for optimising existing..." Document

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#30]
Here is some feedback on the draft aDoc of the guidance. Wasn't sure whether I should be submitting this as an "issue" or a "discussion" so I opted for this. 

·        Intro/General Order: the intro seems to indicate that the focus of the paper will be augmenting existing PPs to allow their TOE in a cloud environment. The intro also mentions that the document will briefly consider how stacking PPs could be used as a future way forward. After the intro though, the section 2 and 3 are geared towards stacking PPs despite this not being identified as the primary use of the guidance. I'd recommend moving these sections toward the end of the guidance to better focus its intent. If I'm incorrect about intent, perhaps a slight re-wording of the intro could help

·        Intro: the third bullet of items that need "future work" indicates that layers of the cloud stack are subject to continual security patching. I think the issue is much deeper than that though. The whole stack is subject to arbitrary software development and sometimes even security relevant changes. For instance, adoption of TLS 1.3 can inherit the 0-RTT security concern, so even though it is considered a modernization effort, it changes the security posture of customers using the evolving environment.

·        Throughout: we use the phrase "basic cloud security certification/approval" several times and then expand with the examples of FedRAMP, etc. I think we need to sharpen our definition a bit. Perhaps something like "certification process recognized/endorsed by a national government supporting common criteria" or something better. It would just be nice to put some limits on what "certification" could mean.

·        Section 3.3: We seem to indicate that the threat model in cloud computing doesn't change from on-prem deployments, but I don't believe that is correct. I think that threat models should include the impact of potential ubiquitous access and threats from multi-tenancy. Both of these could be impactful for a given TOE.

**Comment by jgb1128** [comment]
To be reviewed at next meeting

**Comment by tstodart** [comment]
Here is some feedback on the draft aDoc of the guidance. Wasn't sure whether I should be submitting this as an "issue" or a "discussion" so I opted for this.

· Intro/General Order: the intro seems to indicate that the focus of the paper will be augmenting existing PPs to allow their TOE in a cloud environment. The intro also mentions that the document will briefly consider how stacking PPs could be used as a future way forward. After the intro though, the section 2 and 3 are geared towards stacking PPs despite this not being identified as the primary use of the guidance. I'd recommend moving these sections toward the end of the guidance to better focus its intent. If I'm incorrect about intent, perhaps a slight re-wording of the intro could help

>> I have changed the order and put the PP stack analysis into appendix B (and moved some other bits around to try to get everything consistent). Hopefully this works!

· Intro: the third bullet of items that need "future work" indicates that layers of the cloud stack are subject to continual security patching. I think the issue is much deeper than that though. The whole stack is subject to arbitrary software development and sometimes even security relevant changes. For instance, adoption of TLS 1.3 can inherit the 0-RTT security concern, so even though it is considered a modernization effort, it changes the security posture of customers using the evolving environment.

>> I have added some additional generic text regarding this point to the text, but the 'further work' section is really just a placeholder for issues not resolved by this proposal.

· Throughout: we use the phrase "basic cloud security certification/approval" several times and then expand with the examples of FedRAMP, etc. I think we need to sharpen our definition a bit. Perhaps something like "certification process recognized/endorsed by a national government supporting common criteria" or something better. It would just be nice to put some limits on what "certification" could mean.

>> Added your text.

· Section 3.3: We seem to indicate that the threat model in cloud computing doesn't change from on-prem deployments, but I don't believe that is correct. I think that threat models should include the impact of potential ubiquitous access and threats from multi-tenancy. Both of these could be impactful for a given TOE.

>>Added your examples as possible additions/refinements.
