### ISSUE TITLE
Bare Metal vs Multi-tenant

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#35]
Is Bare Metal required for cloud testing?

Multi Tenant refers to cloud services not application functionality.

This should be discussed at the scheme level.

**Comment by jgb1128** [comment]
Discussion from March 22, 2023:
You need to describe your test environment. Let's examine the bare metal use case.
Parking Lot: ask FedRamp if bare metal testing was done. 
What do PPs typically require: 

- It must be done on an isolated network
- The operational guidance --AGD must be followed (single vs multi must be documented),
- For Vuln analysis--if you have multi-tenant how do you isolate?
- Test activities should describe what to consider and how the op environment can ensure security

Test activities will look the same if this is multi-tenant vs bare metal

**Comment by jgb1128** [comment]
At the IaaS level:  GPCP, DSC possibly Full Drive Encryption likely must be bare metal
At the PaaS level:  GPOS, VMM, DBMS: multi-tenant is fine
At the SaaS level:  either is fine, but guidance is key and will likely require changes compared to on-prem guidance

**Comment by jgb1128** [comment]
Assigned to Anne but she doesn't have an account to ask FedRamp auditors if bare metal testing is done

**Comment by jgb1128** [comment]
Based on the TOEs being evaluated the need to test on bare metal will be generally obvious. Multi-tenant is prevalent generally in use by customers and will likely be the vast majority of use cases for evaluations.

**Comment by jgb1128** [comment]
If FedRamp does any testing on Bare Metal, we would like to know.  @jgs1618 assigned.

**Comment by jgs1618** [comment]
It appears FedRAMP tests on Bare Metal since Oracle has FedRAMP High Authorization for its Government cloud.  
https://www.oracle.com/corporate/pressrelease/oracle-achieves-fedramp-high-authorization-042120.html&cd=19&hl=en&ct=clnk&gl=us

I suggest that Oracle members internally obtain and review the package which ought to include an overview of the testing that is performed on Bare Metal. @jgb1128

**Comment by jgs1618** [comment]
From FedRAMP:  

FedRAMP does authorize bare metal as part of a few of the IaaS offerings. The tests surrounding bare metal are mainly environmental. In order to talk about other types of tests we would have to define bare metal. In some cases there are varying degrees of how stripped down a machine will be given to a customer. A lot of solutions include the hypervisor so there can be inheritance of some base level functions from that. In some cases some transport level cryptography might be a part of the machine or infrastructure that is handed over to the customer. All that being said there is no special testing done for bare metal. The NIST controls that are supported by the bare metal solution and operating environment are tested using the 800-53A test cases as the base for defining specific cases.

**Comment by bharveyTX** [comment]
Closing the issue as we have defined bare metal and added language to address testing at line 470 in the guidance document.
