### ISSUE TITLE
Contributors to Roles in Product Evaluations

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#44]
TOE Developer--the JIL template doesn't have an exact match for a TOE developer.  Here is my proposal:

TOE Developer: Institution (or its agent) responsible for the software, software appliance, or hardware that is the target of the evaluation.

**Comment by mbdowne** [comment]
The JIL document has definitions for each part of the developer: IC manufacturer, ES or AS developer, and card manufacturer. Do we need similar structures? We already have the CSP called out, so wondering if we need to have separate ones for each. Though I do like that you call out the different types, we should consider whether we need the expanded definitions contained in the JIL document where they describe the actual roles. What does "responsible for the software" mean? Is that the person who develops the software? The system owner? The admin? We should be more clear.

**Comment by mbdowne** [comment]
For example, here is the definition from App PP for "developer": An entity that writes application software. For the purposes of this document, vendors and developers are the same. (OS and GPCP have the same thing, but use "OS" instead of "application")

So maybe something like this:
TOE Software Developer: Institution (or its agent) responsible for writing application software.
TOE Platform Developer: Institution (or its agent) responsible for writing platform (or maybe OS?) software.

The official CC definition says "organization responsible for the development of the target of evaluation" - I don't think that's specific enough for our uses here.

**Comment by jgb1128** [comment]
We will go with just TOE Developer: "Organization responsible for the development of the TOE."
