### ISSUE TITLE
Contributors Roles in Product Evaluations

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#45]
Definition of a Cloud Service Provider. 

[Cloud Service Provider](https://cloudsecurityalliance.org/blog/2020/04/30/what-is-a-cloud-service-provider/): A cloud service provider, or CSP, is a company that offers some component of cloud computing; typically when you search the internet a cloud service is defined as, infrastructure as a service (IaaS), software as a service (SaaS) or platform as a service (PaaS) to other businesses or individuals.

**Comment by jgb1128** [comment]
Note NIST does not have one. [Azure](https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-a-cloud-provider/#:~:text=A%20cloud%20service%20provider%20is,use%2C%20as%20business%20demands%20require.) has a good one, but we may not want to take a particular company's definition so I suggest this one from the Cloud Security Alliance.

**Comment by fahmed11** [comment]
Here is a version used in DoD Cloud Computing SRG v1r4 (with a distinction made with CSO):
"A CSP is an entity that offers one or more cloud services in one or more deployment models. A CSP might leverage or outsource services of other organizations and other CSPs (e.g., placing certain servers or equipment in third-party facilities such as data centers, carrier hotels/collocation facilities, and Internet Exchange Points). CSPs offering SaaS may leverage one or more third-party CSOs (i.e., for IaaS or PaaS) to build out a capability or offering. 
A CSO is the actual IaaS/PaaS/SaaS solution available from a CSP. This distinction is important since a CSP may provide several different CSOs"

**Comment by e-newt** [comment]
There is a NIST definition for 'cloud provider' originally published in their reference architecture document: The entity (a person or an organization) responsible for making a service available to interested parties. 

There is also a similar definition for CSP in ISO/IEC 22123-1 (Information technology — Cloud computing — Part 1: Vocabulary):
party which makes cloud services available

Footnotes:
--cloud service is defined as
one or more capabilities offered via cloud computing invoked using a defined interface

--cloud computing is defined as 
paradigm for enabling network access to a scalable and elastic pool of shareable physical or virtual resources with self-service provisioning and administration on-demand

Note 1 to entry: Examples of resources include servers, operating systems, networks, software, applications, and storage equipment.

--You can view these here (as well as the definition of party): 
https://www.iso.org/obp/ui#iso:std:iso-iec:22123:-1:ed-1:v1:en:term:3.4.3

**Comment by jgb1128** [comment]
@bharveyTX  suggest we tackle this one pretty early on.

**Comment by mbdowne** [comment]
There's also this from CNSSP 32 (which uses the same NIST definitions for SaaS/PaaS/IaaS): "A person, organization, or entity responsible for making a service available to service customers."

**Comment by jgb1128** [comment]
Duplicate this is done.
