### ISSUE TITLE
Introduction/Document Layout

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#64]
- The intro for "Guidelines for optimising..." suggests that the focus of the document is updating individual PPs for the cloud and that there is a "brief look" at using a composition of PPs. However, the document immediately jumps into the composition of PPs and spends about half the content length on this. I think we should switch the order and go into the sections on updating individual PPs first if that is the focus
- 4th paragraph "While this approach gives..." is ambiguous. It isn't clear whether this is talking about the approach of updating individual PPs or the document in general
-  Formatting: suggest indenting all of the italicized text under the numbered list. Currently, the italicized lines break up the list rather than naturally being a subcomponent (or answer) to each of the numbered items
- Some of the numbered aspects requiring additional work could use more explanation. A "For example.." would help readers unfamiliar with the topic to grasp the meaning
- The numbered bullets all talk about what is not in this document. The context is different enough that it could be helpful to break this out into its own subsection

**Comment by tstodart** [comment]
Are these comments referring to

**Comment by tstodart** [comment]
Sorry, error

**Comment by tstodart** [comment]
Are the comments referring to version 0.2 of "Guidelines for optimising existing Protection Profiles to enable effective evaluation of TOEs operating in a cloud environment.Version: 0.2"? I spent considerable time re-arranging the order and moving composition to an appendix so I don't understand where this first bullet point is coming from.
"While this approach gives...." yes, indeed. There are clear open item from this proposal as yet unresolved. Please note that this document is input for the main guideance document, where these aspects will be considered further, I hope.
"Formatting/numbering" - I propose not to work on this since this will be merged with main guidance.
"Some of the numbered aspects requiring additional work could use more explanation. A "For example.." would help readers unfamiliar with the topic to grasp the meaning" - agreed, please provide text.
