### ISSUE TITLE
Guidance doc section 3.1 - Useful Terms

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#66]
Suggested terms for cloud:
- Share tenancy
- Data sovereignty

Also, I'd recommend changing the title of 3.1 since we already have a section called "Introduction"

**Comment by tstodart** [comment]
Please provide term definitions.
The second use of 'Introduction' is referring to the first chapter in most PP's. I could change the first one to 'Preface' or something else.

**Comment by compgeeksquires** [comment]
Possible Data sovereignty definitions:
From https://www.techtarget.com/whatis/definition/data-sovereignty:
"Data sovereignty is the concept that information which has been converted and stored in binary digital form is subject to the laws of the country in which it is located."

longer option: from https://cloudian.com/guides/data-protection/data-sovereignty-in-the-cloud-key-considerations/
"Data sovereignty refers to the laws applicable to data because of the country in which it is physically located. The legal rights of data subjects (any individual whose personal information is being gathered, retained, or processed), and data protection requirements, depend on the location in which their data is stored. Accordingly, organizations will have different responsibilities for data in different geographical locations.

Data sovereignty is distinct from data localization and data residency:

Data localization refers to a governmental policy that prohibits organizations from transferring data outside a specific location. It is a special case of data sovereignty.
Data residency is a decision by businesses to store data in a specific geographical location. Organizations might store data in a specific location to avoid legal requirements, take advantage of tax regimes, or for performance reasons. Once an organization chooses a location for its data, it is subject to data sovereignty—the laws applicable in that region."

**Comment by bharveyTX** [comment]
Migrating data sovereignty claims to Scheme Guidance issue.
