### ISSUE TITLE
Lab/Evaluator Instructions

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#74]
To be discussed is a section in the main document around what labs/certifiers need to consider to expand their scope to CCitC.

**Comment by jgb1128** [comment]
Provide guidance to labs (and schemes) on how labs can maintain independence of the testing environment from the Cloud provider.

**Comment by heimannrj** [comment]
I think this comment belongs here but can move it if needed.  I pulled some verbiage together for test environment guidance for consideration/discussion.  I took what was already in the Guidance Doc and expanded it to include concepts of:
•Representative of OE
•Environment isolation
•Access Controls

Test Environment Guidance input

Any cloud testing environment should be logically isolated from the public and have the necessary access controls in place to limit access to the evaluators and TOE developers as needed for testing and evaluation.  Ideally this environment is controlled by the CCTL to ensure adherence to requirements for isolation and integrity of testing and results.  In the event that the CCTL cannot maintain control of the environment, for example if the complexity of the operational environment cannot be replicated in isolation, coordination of testing should be made with the local scheme or governing body to ensure compliance with evaluation requirements (similar to requirements for remote testing).

The evaluator should be prepared to establish test environment(s) representative of the topologies described in the section “Cloud Topology” above within the Cloud Service Provider infrastructure where a product under evaluation is designed to operate and be certified.  The testing environment should be representative of the deployment environment and include those services and functions that would be present in the operational environment for the CSP.  For example, if the TOE is an application designed to operate as a Software as a Service (SaaS), the evaluator will instantiate a like environment that provides the services and functions that will be available in the production and operational environment.  Likewise for TOE(s) designed to operate in Platform and Infrastructure as a Service (PaaS & IaaS) topologies, the test environment should scale accordingly to represent the operational environment.  Components that represent underlying operational functionality for the TOE should NOT be virtualized, emulated, or simulated unless they would otherwise be in the production environment.  Resources and services in Operational Environment are permitted to be provided virtually.

Are test evidence considerations for where/how it is collected in terms of test environmnet an issue?
Constrain test inspection and evidence collection within the test environment?  Pros/cons

-Randy

**Comment by jgb1128** [comment]
So a few initial comments @heimannrj   : 

1. Yes we should aim to simulate in the cloud testing how the product under evaluation will be deployed
2. On the other hand, virtualized environments are how "underlying operational functionality" is deployed.  If it isn't virtualized then are you suggesting physical access would be required?  Virtualization is a mandatory component in almost every deployment scenario. We should walk through what a NON virtualized TOE would look like for CCitC

**Comment by heimannrj** [comment]
Agree this language could be tighter.  The point here was we probably dont want to be testing in simulated cloud environments, but rather inside test environments hosted within the CSP where the TOE is deisgned to operate.  Removing virtualized from this context may clarify this.

**Comment by jgb1128** [comment]
There is a lot of discussion required about how all of this would work. For example would the vendor provide the lease or will they search for labs that work with CSPs which a vendor wants listed on their certificate?  It's easy for Oracle because we are a vendor and a CSP. But for the vast majority of the vendors these issues need to be fleshed out.  I wonder if guidance for evaluators is really something separate compared to guidance for PP authors.  Something worth discussing.

**Comment by heimannrj** [comment]
The test facility is expected to be independant from the vendor and I think this is true for most, if not all, the schemes.  I believe this means the cost of these new test envirnments would be borne by the CCTL.  A CCTL maintaining a test enclave within a CSP seems within the realm of the possible and a neccesity in order to maintain control of the test environment to the maximum extent possible.  At some point, evlauators will need access or output from the low level CSP environment to demonstrate assurance for something and so a special relationship between the CCTL and CSP probably needs to exist.  Whether it is case by case or more formal access to CSP engineers is TBD.  The working group needs input from those CSP SME's to identify those break points and how that assistance could be provided.

As you alluded to, its going to be a possibility (liklihood?) for the TOE vendor to also be the preferred CSP.  When testing at a vendor facility is proposed today, in my experience, it is heavily scrutinized and only approved in specific cases.  The same scrutiny should be applied when a vendor is also the CSP provider.  I dont think this alleviates the CCTL from a establishing their own environment though.  In fact it should strengthen the need for it.  

I would think this guidance would be for the schemes and CCTLs (or scheme equivalants to CCTL) use to help define these new cloud based test environments and how to maintain test/evaluation independance, or at a bare minimum provide enough transparancy to mitigate any doubts.  Whether we cleave this section off is a quesiton for the group.  My opinion is this guidance is going to be digested and applied by the schemes so it should stay.

-Randy

**Comment by jgb1128** [comment]
@heimannrj excellent analysis.  We should discuss on our next call.

**Comment by jgb1128** [comment]
Consider integrating into "Guidance for Establishing Test Environments on Cloud Infrastructure.

**Comment by tstodart** [comment]
Some generalised text based on where I see call-outs regarding the lab in the current guidance (so a bit of a copy-and-paste). Can be used as a start for discussion:

A PP should provide an evaluator with clear explanations tailored to evaluators perhaps limited experience of cloud infrastructure and security. Evaluators should aim to develop their knowledge and techniques for TOEs in the cloud to a comparable level to that for traditional 'on-prem' TOEs.
Evaluators should read the explicit guidance provided within the PP for TOEs in a cloud environment. This may include an appendix as guidance for an evaluator to assess whether the cloud environment for the TOE satisfies the Security Objectives of the Operating Environment of the PP. This will likely include a mapping that may be used by an evaluator to confirm that the selected Trusted Platform has been validated by an appropriate Cloud Authorization Scheme to have controls fulfilling the Assumptions and associated Security Objectives for the Operating Environment. This material should be reviewed and considered carefully. In the case where an evaluator considers that the material provided is insufficient or in error, the evaluator should contact the PP author for further discussion.
Evaluators should also consider guidance in the Protection Profile regarding testing. An evaluator should prepare cloud testing infrastructure for the evaluation. This environment will establish controls provided by the CSP to ensure effective isolation equivalent to on-prem testing to maintain the integrity of results. This may involve isolated VLANs, ACLs, Compute Resources, etc. on multi-tenant infrastructure. This information will need to be captured and presented to Evaluation Authorities as evaluation deliverables.
Evaluators should also consider guidance in the PP regarding vulnerability testing. It may  the case that when applicable vulnerabilities are discovered or suspected for TOEs operating in a cloud environment, the evaluators may be required to utilize cloud attack vectors. I.e. service portal, management plane, etc. to complete the testing.

**Comment by bharveyTX** [comment]
Added Tyrone's content to the guidance doc for review.

**Comment by jgb1128** [comment]
Intentional decision to keep it high level to avoid differentiation between schemes.
