### ISSUE TITLE
Sections that need Work

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#97]
- Shared Security Model
- Editorial in "Equivalence"
- Review roles and see what is relevant
- Guidance for Test Environments

**Comment by jgb1128** [comment]
We are looking for volunteers to review the sections above, and either flesh out, edit, or just write more.

**Comment by jdonndelinger** [comment]
Josh, hopefully, we'll get more than one person working on these, but not too many. With the caveat that I'm going on a two week vacation next week, I'll commit participating in the "guidance for test environments" section. 

~Jim

**Comment by jgb1128** [comment]
> Josh, hopefully, we'll get more than one person working on these, but not too many. With the caveat that I'm going on a two week vacation next week, I'll commit participating in the "guidance for test environments" section.
> 
> ~Jim

Ok Jim. I am going to create an action for you if this is possible in Github.

**Comment by jgb1128** [comment]
@bharveyTX will take the shared security model.
@jdonndelinger please work with Brandon on how to integrate your bits back into the doc.

**Comment by jgb1128** [comment]
@jgb1128 I will take editorial in "Equivalence"

**Comment by jgb1128** [comment]
Still need a volunteer to look at roles.

**Comment by tstodart** [comment]
Had a look at roles, and have some initial thoughts.

The following roles I found use in the text, but not defined in the section.
Roles not defined: 
_Customer (also cloud customer)_ 20+ references.
_consumer_ (10+ references.
_TOE administrator (the CSP customer)_, 15+ references.
_tenant_ (used once in a way that seems a role - regarding bare metal)
_certificate authorizing scheme_ - used only once.
_Certification Authorities_ - used only once.
_lab_ - used in the context of 'CC lab' - may wish to replace with _Evaluator_.
It should be noted that we may want to clarify the use of customer, consumer, TOE administrator, tenant and determine whether any of these are redundant. If not, we need to explain the differences and how they relate to each other.
Similarly for authorities/schemes, etc.

In list: 
_TOE developer(1)_, (used only once)
_Cloud Service Provider_ (25+ see also cloud provider (5))
_Sponsor_ - not used - maybe remove (left from JIL document?)
_Evaluator_ (5), 
_Certification Body_ - also currently not used - remove?
_Evaluation Authority/ies_ (-ies 1) - only used in the preface.
_Cloud Authorization Scheme_ (1) - in both the glossary and the roles - remove from one? Otherwise only in the preface.

Cloud Service Offering - recommend this to be added to the Glossary.

**Comment by tstodart** [comment]
The following roles I found use in the text, but not defined in the section.
Roles not defined:
Customer (also cloud customer) 20+ references. - added
consumer (10+ references. My review is that consumer is used almost entirely in certain sections. No distinction from 'customer'. replaced with customer for consistency.
TOE administrator (the CSP customer), 15+ references. - added adminstrator reference from CC:2022
**tenant (used once in a way that seems a role - regarding bare metal)- needs further review**
certificate authorizing scheme - used only once - replaced with Evaluation Authority
Certification Authorities - used only once - replaced with Evaluation Authorities
lab - used in the context of 'CC lab' - replaced with Evaluator.
It should be noted that we may want to clarify the use of customer, consumer, TOE administrator, tenant and determine whether any of these are redundant. If not, we need to explain the differences and how they relate to each other.
Similarly for authorities/schemes, etc.

In list:
TOE developer(1), (used only once) - shorten to 'developer' 
Cloud Service Provider (25+ see also cloud provider (5))
Sponsor - not used - maybe remove (left from JIL document?) - removed
Evaluator (5),
Certification Body - also currently not used - removed
Evaluation Authority/ies (-ies 1) - only used in the preface. - aligned with CC
Cloud Authorization Scheme (1) - in both the glossary and the roles - remove from one? - removed from roles

Cloud Service Offering - recommend this to be added to the Glossary.

**Comment by tstodart** [comment]
In the Glossary, the following are not used in the text and may be removed, if agreed.
"Multi-Cloud", "Trusted Cloud Service Provider", Cloud Protection Profile Extensions"

**Comment by jgb1128** [comment]
Closing...all tasks tracked in #100
