### ISSUE TITLE
Shared Security Model Section

### ISSUE THREAD

**Issue by bharveyTX** [CC-in-the-Cloud/Admin#98]
1st Draft: 

In the realm of cloud security, the shared security model is a fundamental concept that defines the division of responsibilities between the Cloud Service Provider (CSP) and their customers within a cloud environment. This model acknowledges that while the CSP is responsible for securing the underlying cloud infrastructure, the customer also bears the responsibility of securing their applications, data, and configurations within that infrastructure. The shared security model recognizes that security is a collaborative effort, where both the CSP and the customer play crucial roles. This model is widely embraced in various cloud security frameworks, as it provides a clear model for understanding and allocating security responsibilities in a cloud environment. By delineating these responsibilities, the shared security model helps establish trust, accountability, and transparency between the CSP and the customer, ensuring a holistic approach to cloud security.

This concept is also useful for CCiTC evaluations and mirrors the relationship found with the TOE and TOE Platform. To emphasis the enhanced requirements for Cloud Infrastructure we will refer to the shared responsibility model in terms of the TOE and the Trusted Platform.
In the majority of use cases the TOE administrator (the CSP customer) is responsible for the secure utilization and customization of the cloud services provided by the CSP. This includes managing user access controls, configuring security settings, and implementing appropriate security measures aligned with their specific requirements. These elements may map appropriately to existing SFRs such as FMT_SMF with or without refinement for CCiTC. The TOE administrator ensures that the TOE (cloud tenant) operates securely within the parameters set by the CSP (TOE Platform).

While the CSP maintains the security and availability of the TOE Platform, the TOE administrator (customer) is tasked with safeguarding their applications, data, and configurations within the cloud environment. They actively manage security controls, such as authentication mechanisms, encryption protocols, and network access policies, to protect their assets and mitigate potential risks.

The evaluation and assessment of the shared security model must take into account both the TOE administrator (customer) and the TOE Platform (CSP). The CSP, as the TOE Platform, undergoes evaluation against relevant security standards, certifications, and best practices to demonstrate the effectiveness of the underlying cloud infrastructure's security controls.
Simultaneously, the TOE administrator (customer) is responsible for implementing and managing security controls and configurations within their own cloud environment. They utilize the provided security features, adhere to the CSP's policies and guidelines, and maintain appropriate security configurations to ensure the integrity and confidentiality of their data.
By designating the customer as the TOE administrator, the shared security model reinforces their active involvement in the secure administration of the cloud services. The CSP, as the TOE Platform, provides the underlying infrastructure, while the TOE administrator assumes the responsibility of effectively configuring, managing, and monitoring the TOE to meet their specific security objectives and compliance requirements.

To ensure that customers acting as TOE administrators, who are familiar with Common Criteria but may have limited knowledge of cloud infrastructure and security, can effectively manage the TOE within the shared security model, it is important for the authors of protection profiles to adapt the TOE Security Specifications (TSS) and Administrator Guidance Document (AGD) requirements accordingly. This includes providing clear instructions, accessible language, and practical guidance tailored to TOE administrators. By modifying the TSS and AGD requirements in this manner, the authors of protection profiles can ensure that TOE administrators can confidently manage the TOE within the shared security model, bridging the gap between Common Criteria expertise and the challenges of managing security in a cloud environment.
To ensure that customers acting as TOE administrators, who are familiar with Common Criteria but may have limited knowledge of cloud infrastructure and security, can effectively manage the Target of Evaluation (TOE) within the shared security model, it is important for the authors of protection profiles to adapt the TOE Security Specifications (TSS) and Administrator Guidance Document (AGD) requirements accordingly.

The TSS, which defines the security functionality and assurance requirements of the TOE, can be modified by the authors of protection profiles to provide clear instructions and explanations tailored to TOE administrators with limited knowledge of cloud infrastructure and security. The modified TSS should include detailed guidance on how to configure and customize the TOE in a secure manner, specifying recommended security controls and configuration options. This information should be presented in an easily understandable language, using plain terms and avoiding technical jargon whenever possible.

Similarly, the AGD, which offers guidance on the secure deployment, configuration, and maintenance of the TOE, should be modified to provide step-by-step instructions and best practices that are accessible to TOE administrators. The updated AGD should cover essential topics such as user access management, secure authentication methods, data encryption, incident response procedures, and other pertinent security considerations. The guidance should be written in a user-friendly and non-technical manner, focusing on practical advice and highlighting potential security pitfalls that TOE administrators may encounter.

By adapting the TSS and AGD requirements in this manner, the authors of protection profiles can ensure that TOE administrators with limited knowledge of cloud infrastructure and security can confidently manage the TOE within the shared security model. These modifications provide clear and accessible guidance, empowering TOE administrators to make informed decisions, configure the TOE securely, and fulfill their security responsibilities effectively.

**Comment by bharveyTX** [comment]
Initial Discussion:

Add additional language for auditing and logging. Give some examples for PP authors to consider when the TOE must provide log information to the cloud platform or vice versa. 

We need to add in the TOE Vendor into the section that explains that additional deployment model. The TOE vendor may be responsible for TOE trusted updates and patching while the CSP and TOE admin are not.

We need to make sure that it's clear that the TOE is part of the cloud stack in our use cases and not necessarily a piece of hardware that is installed in a cloud environment.

Rewrite paragraph on line 179 to specify that the TSS is not providing instructions or guidance but rather information to evaluators and ST readers.

**Comment by bharveyTX** [comment]
Suggest writing in section that the base PP audit selections may need to reference the TOE or TOE Platform to allow for CSP provided services to be changed in a cloud-specific module.

**Comment by bharveyTX** [comment]
Need to include an example of the audit selection refinement

**Comment by bharveyTX** [comment]
Add a pointer in the shared security model section for the SFR TOE Platform refinements to Steps to Optimize -> SFR section. Include example from MDM and TLS failures, NDcPP and FIA_UAU_ and PP_OS for system reboot.

**Comment by jgb1128** [comment]
"These elements may map appropriately to
existing SFRs such as FMT_SMF with or without refinement for CCiTC."
**Spell out first use of FMT_SMF.**  We should not use CC jargon without full reference the first time.

'While the CSP maintains the security and availability of the TOE Platform, the TOE administrator
(customer) is tasked with safeguarding their applications, data, and configurations within the cloud
environment."

Change to:  "While the CSP maintains the security and availability of the TOE Platform, the TOE administrator
(customer) is **assumed to be**  tasked with safeguarding their applications, data, and configurations within the cloud
environment."

"The CSP, as the TOE Platform, undergoes evaluation against relevant security standards, certifications, and best practices to demonstrate the effectiveness of the underlying cloud infrastructure’s security controls."
Add this after: "See the Trusted Platform section for more information on the required security assessments for the TOE Platform."

"...the TOE or TSFI"
**Spell out TSFI first use.**

"...certain Common Criteria (CC) requirements"
**remove "Common Criteria" as CC has already been spelled out in the doc.**  I think there a several examples where you don't need to spell out Common Criteria.

**Comment by bharveyTX** [comment]
Editorial changes have been made. As no other feedback has been received for the section we are closing the issue and marking as done.

**Comment by jgb1128** [comment]
Draft in Sept 27th version:
In the realm of cloud security, the shared security model is a fundamental concept that defines the
division of responsibilities between the Cloud Service Provider (CSP) and their customers within a
cloud environment. This model acknowledges that while the CSP is responsible for securing the
underlying cloud infrastructure, the customer also bears the responsibility of securing their
applications, data, and configurations within that infrastructure based on the service model. The
shared security model recognizes that security is a collaborative effort, where both the CSP and the
customer play crucial roles. This model is widely embraced in various cloud security frameworks,
as it provides a clear model for understanding and allocating security responsibilities in a cloud
environment. By delineating these responsibilities, the shared security model helps establish trust,
accountability, and transparency between the CSP and the customer, ensuring a holistic approach
to cloud security.
This concept is also useful for CCiTC evaluations and mirrors the relationship found with the TOE
and TOE Platform. To emphasize the enhanced requirements for Cloud Infrastructure we will refer
to the shared responsibility model in terms of the TOE and the Trusted Platform.
In the majority of use cases the TOE administrator (the CSP customer) is responsible for the secure
utilization and customization of the cloud services provided by the CSP. This includes managing
user access controls, configuring security settings, and implementing appropriate security
measures aligned with their specific requirements. These elements may map appropriately to
existing SFRs such as management functions defined by the FMT class in CC Part 2 (FMT_SMF) with
or without refinement for CCiTC. The TOE administrator ensures that the TOE (cloud tenant)
operates securely within the parameters set by the CSP (TOE Platform).
While the CSP maintains the security and availability of the TOE Platform, the TOE administrator
(customer) is assumed to be tasked with safeguarding their applications, data, and configurations
within the cloud environment. They actively manage security controls, such as authentication
mechanisms, encryption protocols, and network access policies, to protect their assets and mitigate
potential risks.
The evaluation and assessment of the shared security model must take into account both the TOE
administrator (customer) and the TOE Platform (CSP). The CSP, as the TOE Platform, undergoes
evaluation against relevant security standards, certifications, and best practices to demonstrate the
effectiveness of the underlying cloud infrastructure’s security controls. See the Trusted Platform
section for more information on the required security assessments for the TOE Platform.
Simultaneously, the TOE administrator (customer) is responsible for implementing and managing
security controls and configurations within their own cloud environment. They utilize the provided
security features, adhere to the CSP’s policies and guidelines, and maintain appropriate security
configurations to ensure the integrity and confidentiality of their data.
There are certain areas where the shared security model can be somewhat blurred. For example,
with many CC evaluations, the TOE or TOE Security Functional Interface (TSFI) is expected to
exclusively generate TOE audit events. In the context of a virtualized network device deployed on a
public cloud, certain CC requirements, such as FAU_GEN.1 (Audit Generation), would need to be
modified to account for the consumption of logs provided by the Cloud Service Provider (CSP).
FAU_GEN.1 requires the TOE (virtualized network device) to generate audit records for security relevant
events. However, in a cloud environment, the CSP typically manages the underlying
infrastructure and maintains centralized logging systems. As a result, the TOE may rely on the CSP’s
log management capabilities and consume the logs provided by the CSP rather than generating its
own audit records.
To accommodate this scenario, the collaborative protection profile for the virtualized network
device on the public cloud should specify the requirements for log consumption from the CSP’s
logging infrastructure. This would include defining the format, content, and frequency of logs to be
provided by the CSP. Additionally, the protection profile should address the integrity and
confidentiality of these logs during transmission and storage.
The modified CC requirements would then focus on the TOE’s capability to securely receive,
process, and analyze the logs provided by the CSP. The TOE should be able to extract relevant
security events from the logs and correlate them with its own internal security policies.
Furthermore, it should have the ability to raise alerts or initiate appropriate actions based on the
analysis of the consumed logs.
By adapting CC requirements like FAU_GEN.1 to encompass log consumption from the CSP, the
protection profile enables the virtualized network device to leverage the logging capabilities
provided by the CSP while maintaining compliance with CC standards. This ensures that security relevant
events are properly logged, analyzed, and acted upon in the cloud environment,
contributing to a comprehensive security posture for the virtualized network device.
Additionally, it may be important to add a third element to the shared security model for CCiTC
evaluations. This would be the inclusion of the TOE Vendor in addition to the TOE Administrator
and CSP. The TOE Vendor may be responsible for providing TOE security updates, maintaining a
trusted update channel and infrastructure, or even applying these updates on behalf of the TOE
Administrator. This is a common feature with traditional SaaS use cases. In such cases where a TOE
vendor is expected to share responsibilities in the security model, PP Authors must make the
appropriate refinements, additions, or iterations of related elements in their PPs. This is a scenario
that may be more common in TOE types that are meant to incorporate physical hardware into
Cloud Infrastructure such as an HSM. However, CCiTC evaluations are not limited to a particular
deployment model. It is also expected that there will be evaluations of TOEs that are integral to a
CSPs cloud stack from hardware to application layers.
Ultimately, by designating the customer as the TOE administrator, the shared security model
reinforces their active involvement in the secure administration of the cloud services. The CSP, as
the TOE Platform, provides the underlying infrastructure, while the TOE administrator assumes the
responsibility of effectively configuring, managing, and monitoring the TOE to meet their specific
security objectives and compliance requirements.
To ensure that customers acting as TOE administrators, who are familiar with Common Criteria but
may have limited knowledge of cloud infrastructure and security, can effectively manage the TOE
within the shared security model, it is important for the authors of protection profiles to adapt the
Administrator Guidance Document (AGD) requirements accordingly. This includes providing clear
instructions, accessible language, and practical guidance tailored to TOE administrators. By
modifying the AGD requirements in this manner, the authors of protection profiles can ensure that
TOE administrators can confidently manage the TOE within the shared security model, bridging the
gap between Common Criteria expertise and the challenges of managing security in a cloud
environment.
Additionally, The TSS, which defines the security functionality and assurance requirements of the
TOE, can be modified by the authors of protection profiles to provide clear explanations tailored to
evaluators limited knowledge of cloud infrastructure and security. The modified TSS should include
detailed information such that it is clear how the TSFI or SFR enforcing features interact in a cloud
context with the TOE Platform.
By adapting the TSS and AGD requirements in this manner, the authors of protection profiles can
ensure that TOE administrators with limited knowledge of cloud infrastructure and security can
confidently manage the TOE within the shared security model. These modifications provide clear
and accessible guidance, empowering TOE administrators to make informed decisions, configure
the TOE securely, and fulfill their security responsibilities effectively.
